---
title: "Homework1"
output: html_notebook
---

```{r}
library("quantmod")
library("e1071")
require("quantmod")
library(ggplot2)
```

```{r echo=FALSE, message=TRUE, warning=TRUE, paged.print=TRUE}
sp500 <- new.env()
getSymbols("^GSPC", env = sp500, src = "yahoo", from = as.Date("1960-01-04"), to = as.Date("2009-01-01"))
GSPC <- sp500$GSPC
```

```{r}
SP500 <-read.csv("SP500constituentsSecid2016sector.csv", stringsAsFactors = FALSE, strip.white = TRUE)
SP500['Ticker']
```

```{r}
SP500 <- read.csv("SP500constituentsSecid2016sector.csv", header=TRUE, sep=",")
sp<- new.env()
listEnterprise <- c()
for(i in SP500$Ticker){
  cat("Downloading time series for symbol '", i, "' ...\n", sep = "")
  status <- tryCatch(getSymbols(i, env = sp, src = "yahoo", from = as.Date("2007-01-01")), error = identity)
  if(inherits(status, "error")) cat("Symbol '", i, "' not downloadable!\n", sep = "")
  else{
    listEnterprise <- c(listEnterprise, i)
  }
}
```
Question 1
Building of the matrix with the mean, the variance, the skewness and kurtosis
```{r}
moyenne <- c()
variance <- c()
skew <- c()
kurto <- c()
for(i in listEnterprise){
  a = getSymbols(i, auto.assign = FALSE, from = as.Date("2007-01-01"))
  adjusted = Ad(a)
  moyenne <- c(moyenne,mean(adjusted))
  variance <- c(variance,sqrt(var(adjusted)))
  skew <- c(skew, skewness(adjusted))
  kurto <- c(kurto, kurtosis(adjusted))
}
moyenne = na.omit(moyenne)
variance = na.omit(variance)
skew = na.omit(skew)
kurto = na.omit(kurto)
SP500Matrix <- c(moyenne, variance, skew, kurto)
SP500Matrix <- matrix(SP500Matrix, byrow=TRUE, nrow = 4)
```
Nonparametric density estimates
```{r}
cat("The mean of the mean of comapanys is",mean(moyenne),"whereas its medianne is equal to", median(moyenne))
```

```{r}
cat("The mean of the variance of comapanys is",mean(variance),"whereas its medianne is equal to", median(variance))
```

```{r}
cat("The mean of the skewness of comapanys is",mean(skew),"whereas its medianne is equal to", median(skew))
```

```{r}
cat("The mean of the kurtosis of comapanys is",mean(kurto),"whereas its medianne is equal to", median(kurto))
```
```{r}
moyennedf = data.frame(moyenne)
gg = ggplot(data =moyennedf, aes(x=moyenne)) + geom_histogram(binwidth=5, colour="black", aes(y=..density.., fill=..count..))
gg = gg + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")
gg = gg + stat_function(fun=dnorm, color="red",args=list(mean=mean(moyenne), sd=sd(moyenne))) 
gg = gg + ggtitle("Histogramm of the mean")
gg
```
```{r}
moyennedf = data.frame(variance)
gg = ggplot(data =moyennedf, aes(x=variance)) + geom_histogram(binwidth=10, colour="black", aes(y=..density.., fill=..count..))
gg = gg + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")
gg = gg + stat_function(fun=dnorm, color="red",args=list(mean=mean(variance), sd=sd(variance))) 
gg = gg + ggtitle("Histogramm of the variance")
gg
```
```{r}
moyennedf = data.frame(skew)
gg = ggplot(data =moyennedf, aes(x=skew)) + geom_histogram(binwidth=0.1, colour="black", aes(y=..density.., fill=..count..))
gg = gg + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")
gg = gg + stat_function(fun=dnorm, color="red",args=list(mean=mean(skew), sd=sd(skew))) 
gg = gg + ggtitle("Histogramm of the skewness")
gg
```
```{r}
moyennedf = data.frame(kurto)
gg = ggplot(data =moyennedf, aes(x=kurto)) + geom_histogram(binwidth=0.2, colour="black", aes(y=..density.., fill=..count..))
gg = gg + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")
gg = gg + stat_function(fun=dnorm, color="red",args=list(mean=mean(kurto), sd=sd(kurto))) 
gg = gg + ggtitle("Histogramm of the kurtosis coefficient")
gg
```
We can see 

Question3
```{r}
moyenne3 <- c()
variance3 <- c()
skew3 <- c()
kurto3 <- c()
for(i in listEnterprise){
  a = getSymbols(i, auto.assign = FALSE, to = as.Date("2007-01-01"))
  adjusted = Ad(a)
  moyenne3 <- c(moyenne3,mean(adjusted))
  variance3 <- c(variance3,sqrt(var(adjusted)))
  skew3 <- c(skew3, skewness(adjusted))
  kurto3 <- c(kurto3, kurtosis(adjusted))
}
moyenne3 = na.omit(moyenne3)
variance3 = na.omit(variance3)
skew3 = na.omit(skew3)
kurto3 = na.omit(kurto3)
SP500Matrix3 <- c(moyenne3, variance3, skew3, kurto3)
SP500Matrix3 <- matrix(SP500Matrix3, byrow=TRUE, nrow = 4)
```
```{r}
moyennedf3 = data.frame(moyenne3)
gg = ggplot(data =moyennedf3, aes(x=moyenne3)) + geom_histogram(binwidth=5, colour="black", aes(y=..density.., fill=..count..))
gg = gg + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")
gg = gg + stat_function(fun=dnorm, color="red",args=list(mean=mean(moyenne3), sd=sd(moyenne3))) 
gg = gg + ggtitle("Histogramm of the mean before 2007")
gg
```
```{r}

```

```{r}

```

```{r}

```

